- name: create ec2-instances and route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0c195199385efdbc6
    ami_id: ami-0220d79f3f480ecf5
    domain_name: chakri.sbs
    env: dev
    action: create
    instances:
    - mongodb
    - redis
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2:
        instance_type: t3.micro
        image: "{{ ami_id }}"
        sg: "{{ sg_id }}"
        name: "{{ item }}-{{ env }}
        tag:
          Name: "{{ item }}-{{ env }} 
          project: roboshop
          env: "{{ env }}"  
          component: "{{ item }}"
        loop: "{{ instances }}"
        register: ec2_output
        when: action == "create"
