---
- name: create ec2-instances and route53 records
  hosts: all
  connection: local
  vars:
   sg_id: "sg-092464f7c3ff76b0c"
   ami_id: "ami-0220d79f3f480ecf5"
   env: "dev"
   insatnces:
     - mongodb
     - catalogue
  tasks:
   - name: start an instance with a public IP address
     amazon.aws.ec2_instance:
      name: "{{ item }}-{{ env }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}" 
      image_id: "{{ ami_id}}"
      tags:
       Environment: "{{ env }}"
       Name: "{{ item }}-{{ env }}" 
       component: "{{ item }}"