- name: create ec2-instances and route53 records
  hosts: all
  connection: local

  vars:
    sg_id: sg-0c195199385efdbc6
    ami_id: ami-0220d79f3f480ecf5
    domain_name: chakri.sbs
    env: dev
    action: create
    instances:
      - mongodb
      - redis

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Name: "{{ item }}-{{ env }}"
          Project: roboshop
          Environment: "{{ env }}"
          Component: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output
      when: action == "create"
