- name: create instances and route53 record
  hosts: all
  connection: local
  vars:
    sg_id: "sg-092464f7c3ff76b0c"
    ami_id: "ami-0220d79f3f480ecf5"
    env : "dev"
    domain_name: "chakri.sbs"
    instances:
     - mongodb
     - redis
  tasks:
   - name: start an instances with a public IP address
     amazon.aws.ec2_instance:
      instance_type: t3.micro  
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
      name: "{{ instances }}-{{ env }}.{{ domain_name }}"
      tags:
        Name: "{{ instances }}-{{ env }}.{{ domain_name }}" 
        Project: "roboshop"
        component: "{{ instances }}"
        env: "{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

   - name: print ec2_output
     debug:
      msg: "{{ ec2_output }}"